### ISSUE TITLE
不能关闭全部票，会剩5票，再次关闭，会 panic

### ISSUE THREAD

**Issue by YingQm** [yccproject/ycc#6]
pos33 close 不能关闭所有的票，mining 地址还被冻结 50000 ycc。

**Comment by YingQm** [comment]
如果再次调用 pos33 close，会 panic

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x10b12a9]

goroutine 7430 [running]:
github.com/yccproject/ycc/plugin/dapp/pos33/wallet.(*ticketPolicy).On_ClosePos33Tickets.func1(0x0, 0x1816de0, 0xc002af6b60, 0xc000087040)
	/Users/w/pos33/ycc/plugin/dapp/pos33/wallet/exec.go:20 +0x29
created by github.com/yccproject/ycc/plugin/dapp/pos33/wallet.(*ticketPolicy).On_ClosePos33Tickets
	/Users/w/pos33/ycc/plugin/dapp/pos33/wallet/exec.go:19 +0x22e
